import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { FITNESS_ROUTES } from '@/features/fitness/constants/routes'

const navigationConfig: NavigationTree[] = [
    {
        key: 'fitness.dashboard',
        path: FITNESS_ROUTES.dashboard,
        title: 'Tableau de bord',
        translateKey: 'nav.fitness.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'fitness.training',
        path: FITNESS_ROUTES.trainingRoot,
        title: 'Entraînement',
        translateKey: 'nav.fitness.training.title',
        icon: 'training',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'fitness.training.library',
                path: FITNESS_ROUTES.trainingLibrary,
                title: 'Bibliothèque d’exercices',
                translateKey: 'nav.fitness.training.library',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fitness.training.templates',
                path: FITNESS_ROUTES.trainingTemplates,
                title: 'Modèles de séances',
                translateKey: 'nav.fitness.training.templates',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fitness.training.today',
                path: FITNESS_ROUTES.trainingToday,
                title: 'Séance du jour',
                translateKey: 'nav.fitness.training.today',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fitness.training.history',
                path: FITNESS_ROUTES.trainingHistory,
                title: 'Historique',
                translateKey: 'nav.fitness.training.history',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'fitness.body',
        path: FITNESS_ROUTES.bodyRoot,
        title: 'Corps',
        translateKey: 'nav.fitness.body.title',
        icon: 'body',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'fitness.body.weight',
                path: FITNESS_ROUTES.bodyWeight,
                title: 'Poids',
                translateKey: 'nav.fitness.body.weight',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fitness.body.measurements',
                path: FITNESS_ROUTES.bodyMeasurements,
                title: 'Mensurations',
                translateKey: 'nav.fitness.body.measurements',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'fitness.progress',
        path: FITNESS_ROUTES.progress,
        title: 'Progression',
        translateKey: 'nav.fitness.progress',
        icon: 'progress',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'fitness.account',
        path: FITNESS_ROUTES.account,
        title: 'Compte',
        translateKey: 'nav.fitness.account',
        icon: 'account',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'fitness.admin',
        path: FITNESS_ROUTES.adminRoot,
        title: 'Admin',
        translateKey: 'nav.fitness.admin.title',
        icon: 'admin',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'fitness.admin.dev',
                path: FITNESS_ROUTES.adminDev,
                title: 'Dev',
                translateKey: 'nav.fitness.admin.dev',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
