import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { ADMIN, USER } from '@/constants/roles.constant'

const navigationConfig: NavigationTree[] = [
    // Home
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // Stats Section
    /*{
        key: 'stats',
        path: '',
        title: 'Stats',
        translateKey: 'nav.stats',
        icon: 'stats',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'stats.revenue',
                path: '/stats/revenue',
                title: 'Revenue',
                translateKey: 'nav.stats.revenue',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },

        ],
    },
    // Website Section
    {
        key: 'website',
        path: '',
        title: 'Website',
        translateKey: 'nav.website',
        icon: 'website',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'website.stats',
                path: '/website/stats',
                title: 'Stats',
                translateKey: 'nav.website.stats',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'website.orders',
                path: '/website/orders',
                title: 'Orders',
                translateKey: 'nav.website.orders',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'website.customers',
                path: '/website/customers',
                title: 'Customers',
                translateKey: 'nav.website.customers',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'website.reviews',
                path: '/website/reviews',
                title: 'Reviews Generator',
                translateKey: 'nav.website.reviews',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    // Etsy Section
    {
        key: 'etsy',
        path: '',
        title: 'Etsy',
        translateKey: 'nav.etsy',
        icon: 'etsy',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'etsy.messages',
                path: '/etsy/messages',
                title: 'Messages',
                translateKey: 'nav.etsy.messages',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'etsy.stats',
                path: '/etsy/stats',
                title: 'Stats',
                translateKey: 'nav.etsy.stats',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'etsy.reviews',
                path: '/etsy/reviews',
                title: 'Reviews',
                translateKey: 'nav.etsy.reviews',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'etsy.rankings',
                path: '/etsy/rankings',
                title: 'Rankings',
                translateKey: 'nav.etsy.rankings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'etsy.followup',
                path: '/etsy/followup',
                title: 'Followup Reminder',
                translateKey: 'nav.etsy.followup',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'etsy.discounts',
                path: '/etsy/discounts',
                title: 'Discount Generator',
                translateKey: 'nav.etsy.discounts',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'etsy.scraper',
                path: '/etsy/scraper',
                title: 'Scraper',
                translateKey: 'nav.etsy.scraper',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            }
        ],
    },
    */
    // Products Section
    {
        key: 'products',
        path: '/products',
        title: 'Products',
        translateKey: 'nav.products',
        icon: 'products',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [
            // {
            //     key: 'products.manage',
            //     path: '/products',
            //     title: ' Products',
            //     translateKey: 'nav.products.manage',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
        ],
    },
    /*
    // Tools Section
    {
        key: 'tools',
        path: '/tools',
        title: 'Tools',
        translateKey: 'nav.tools',
        icon: 'tools',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'tools.reviews',
                path: '/tools/reviews',
                title: 'Reviews Generator',
                translateKey: 'nav.tools.reviews',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'tools.licenses',
                path: '/tools/licenses',
                title: 'Licenses Generator',
                translateKey: 'nav.tools.licenses',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'tools.upload',
                path: '/tools/upload',
                title: 'Refresh Database',
                translateKey: 'nav.tools.upload',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    */
    // {
    //     key: 'account',
    //     path: '/account',
    //     title: 'Account',
    //     translateKey: 'nav.account',
    //     icon: 'account',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'account.settings',
    //             path: `/account/settings/profile`,
    //             title: 'Settings',
    //             translateKey: 'nav.account.settings',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // }
]

export default navigationConfig
